// Ghost CRT: Blink Shell Theme
// Ported from Ghostty ghost profile + Calibrated WebKit CRT Shaders
// Generated by Ghost CRT Live Studio

const black        = '#1A0F00';
const red          = '#C45A00';
const green        = '#FF9100';
const yellow       = '#FFC107';
const blue         = '#B26A00';
const magenta      = '#D97706';
const cyan         = '#F59E0B';
const white        = '#FEF3C7';

const lightBlack   = '#E29E79';
const lightRed     = '#EA580C';
const lightGreen   = '#F97316';
const lightYellow  = '#FBBF24';
const lightBlue    = '#B45309';
const lightMagenta = '#D97706';
const lightCyan    = '#FB923C';
const lightWhite   = '#FFEDD5';

// 1. Paleta ANSI calibrada (16 tons CRT)
t.prefs_.set('color-palette-overrides', [
  black, red, green, yellow,
  blue, magenta, cyan, white,
  lightBlack, lightRed, lightGreen, lightYellow,
  lightBlue, lightMagenta, lightCyan, lightWhite
]);

// 2. Cores base do terminal
t.prefs_.set('background-color', '#0E0801');
t.prefs_.set('foreground-color', '#FFB300');
t.prefs_.set('cursor-color', '#FFB300');
t.prefs_.set('cursor-blink', true);

// 3. Efeitos CRT calibrados
const crtCss = `
.x-row, .x-row span, x-row, x-row span {
          text-shadow:
    0 0 2.5px rgba(89, 255, 142, 0.18);
        }
        
        .x-scrollport::before, x-scrollport::before {
          content: " ";
          display: block;
          position: absolute;
          top: 0; left: 0; right: 0; bottom: 0;
          background: linear-gradient(
            rgba(0, 0, 0, 0) 75%,
            rgba(0, 0, 0, 0.30) 75%
          );
          background-size: 100% 1px;
          pointer-events: none;
          z-index: 10;
        }
        
        .x-scrollport::after, x-scrollport::after {
          content: " ";
          display: block;
          position: absolute;
          top: 0; left: 0; right: 0; bottom: 0;
          background: radial-gradient(ellipse at 50% 45%, rgba(89, 255, 142, 0.14) 0%, transparent 70%),
                  radial-gradient(ellipse at center, transparent 60%, rgba(0, 0, 0, 0.30) 100%);
          pointer-events: none;
          z-index: 11;
        }
        @keyframes cursorBlink {
          0%, 49% { opacity: 1; }
          50%, 100% { opacity: 0; }
        }
`;

t.prefs_.set('user-css-text', crtCss);
