// Ghost CRT: Blink Shell Theme
// Ported from Ghostty ghost profile + Calibrated WebKit CRT Shaders
// Generated by Ghost CRT Live Studio
// studio-state: {"enableBloom":true,"coreRadius":2.2,"coreOpacity":0.96,"haloRadius":9,"haloOpacity":0.7,"bloomAura":22,"enableScanlines":true,"scanProfile":"dura","scanHeight":4,"scanDarkness":0.46,"scanDuty":50,"enableGrille":false,"grilleMode":"mono","grilleWidth":1.5,"grilleDarkness":0.2,"grilleDuty":33,"enableTube":true,"ambientGlow":0.06,"vignetteDarkness":0.26,"brightness":1,"glare":true,"flicker":false,"fontFamily":"'Terminess Nerd Font Mono', monospace","fontSize":16,"lineHeight":2.02,"letterSpacing":3,"background":"#000000","foreground":"#59ff8e","cursor":"#59ff8e","palette":["#0a130c","#529665","#6edb90","#95e8a7","#43996d","#6cb887","#73d6a6","#99f2b8","#386847","#76c48d","#88f2a9","#affacd","#6cc998","#95e2b0","#90f2be","#c2fce0"]}

const black        = '#0a130c';
const red          = '#529665';
const green        = '#6edb90';
const yellow       = '#95e8a7';
const blue         = '#43996d';
const magenta      = '#6cb887';
const cyan         = '#73d6a6';
const white        = '#99f2b8';

const lightBlack   = '#386847';
const lightRed     = '#76c48d';
const lightGreen   = '#88f2a9';
const lightYellow  = '#affacd';
const lightBlue    = '#6cc998';
const lightMagenta = '#95e2b0';
const lightCyan    = '#90f2be';
const lightWhite   = '#c2fce0';

// 1. Paleta ANSI calibrada (16 tons CRT)
t.prefs_.set('color-palette-overrides', [
  black, red, green, yellow,
  blue, magenta, cyan, white,
  lightBlack, lightRed, lightGreen, lightYellow,
  lightBlue, lightMagenta, lightCyan, lightWhite
]);

// 2. Cores base do terminal
t.prefs_.set('background-color', '#000000');
t.prefs_.set('foreground-color', '#59ff8e');
t.prefs_.set('cursor-color', '#59ff8e');
t.prefs_.set('cursor-blink', true);

// 3. Efeitos CRT calibrados
const crtCss = `
.x-row, .x-row span, x-row, x-row span {
          text-shadow:
    0 0 2.2px rgba(89, 255, 142, 0.96),
    0 0 9px rgba(89, 255, 142, 0.70),
    0 0 22px rgba(89, 255, 142, 0.32);
        }
        
        .x-scrollport::before, x-scrollport::before {
          content: " ";
          display: block;
          position: absolute;
          top: 0; left: 0; right: 0; bottom: 0;
          background-image: linear-gradient(
            rgba(0, 0, 0, 0) 50%,
            rgba(0, 0, 0, 0.46) 50%
          );
          background-size: 100% 4px;
          pointer-events: none;
          z-index: 10;
        }
        x-screen::before {
          content: " ";
          display: block;
          position: absolute;
          top: 0; left: 0; right: 0; bottom: 0;
          background-image: linear-gradient(
            rgba(0, 0, 0, 0) 50%,
            rgba(0, 0, 0, 0.46) 50%
          );
          background-size: 100% 4px;
          pointer-events: none;
          z-index: 100;
        }
        
        
        .x-scrollport::after, x-scrollport::after {
          content: " ";
          display: block;
          position: absolute;
          top: 0; left: 0; right: 0; bottom: 0;
          background: radial-gradient(ellipse at 50% 45%, rgba(89, 255, 142, 0.06) 0%, transparent 70%),
                  radial-gradient(ellipse at center, transparent 60%, rgba(0, 0, 0, 0.26) 100%);
          pointer-events: none;
          z-index: 11;
        }
        x-screen::after {
          content: " ";
          display: block;
          position: absolute;
          top: 0; left: 0; right: 0; bottom: 0;
          background: radial-gradient(ellipse at 50% 45%, rgba(89, 255, 142, 0.06) 0%, transparent 70%),
                  radial-gradient(ellipse at center, transparent 60%, rgba(0, 0, 0, 0.26) 100%);
          pointer-events: none;
          z-index: 101;
        }
        @keyframes cursorBlink {
          0%, 49% { opacity: 1; }
          50%, 100% { opacity: 0; }
        }
`;

t.prefs_.set('user-css-text', crtCss);
