// Ghost CRT: Blink Shell Theme
// Ported from Ghostty ghost profile + Calibrated WebKit CRT Shaders
// Generated by Ghost CRT Live Studio
// studio-state: {"enableBloom":true,"coreRadius":1.8,"coreOpacity":1,"haloRadius":8.5,"haloOpacity":0.6,"bloomAura":18,"enableScanlines":true,"scanProfile":"triangular","scanHeight":2,"scanDarkness":0.2,"scanDuty":50,"scanMode":"fixed","scanPerRow":11,"enableGrille":false,"grilleMode":"mono","grilleWidth":1.5,"grilleDarkness":0.2,"grilleDuty":33,"enableTube":true,"ambientGlow":0.1,"vignetteDarkness":0.26,"brightness":1.1,"textMargin":12,"glare":true,"flicker":false,"background":"#0a0515","foreground":"#ff71ce","cursor":"#01cdfe","palette":["#120824","#ff5376","#05ffa1","#fffb96","#01cdfe","#b967ff","#01cdfe","#fffb96","#2c1654","#ff71ce","#05ffa1","#fffb96","#01cdfe","#d084ff","#70e7ff","#ffffff"]}

const black        = '#120824';
const red          = '#ff5376';
const green        = '#05ffa1';
const yellow       = '#fffb96';
const blue         = '#01cdfe';
const magenta      = '#b967ff';
const cyan         = '#01cdfe';
const white        = '#fffb96';

const lightBlack   = '#2c1654';
const lightRed     = '#ff71ce';
const lightGreen   = '#05ffa1';
const lightYellow  = '#fffb96';
const lightBlue    = '#01cdfe';
const lightMagenta = '#d084ff';
const lightCyan    = '#70e7ff';
const lightWhite   = '#ffffff';

// 1. Paleta ANSI calibrada (16 tons CRT)
t.prefs_.set('color-palette-overrides', [
  black, red, green, yellow,
  blue, magenta, cyan, white,
  lightBlack, lightRed, lightGreen, lightYellow,
  lightBlue, lightMagenta, lightCyan, lightWhite
]);

// 2. Cores base do terminal
t.prefs_.set('background-color', '#0a0515');
t.prefs_.set('foreground-color', '#ff71ce');
t.prefs_.set('cursor-color', '#01cdfe');
t.prefs_.set('cursor-blink', true);

// 3. Efeitos CRT calibrados
const crtCss = `
.x-row, .x-row span, x-row, x-row span {
          text-shadow:
    0 0 1.8px rgba(255, 113, 206, 1.00),
    0 0 8.5px rgba(255, 113, 206, 0.60),
    0 0 18px rgba(255, 113, 206, 0.27);
        }
        
        .x-scrollport::before, x-scrollport::before {
          content: " ";
          display: block;
          position: absolute;
          top: 0; left: 0; right: 0; bottom: 0;
          background-image: linear-gradient(
            rgba(0, 0, 0, 0) 50%,
            rgba(0, 0, 0, 0.20) 75%,
            rgba(0, 0, 0, 0) 100%
          );
          background-size: 100% 2px;
          background-position: 12px 12px;
          pointer-events: none;
          z-index: 10;
        }
        body::before {
          content: " ";
          display: block;
          position: fixed;
          top: 0; left: 0; right: 0; bottom: 0;
          background-image: linear-gradient(
            rgba(0, 0, 0, 0) 50%,
            rgba(0, 0, 0, 0.20) 75%,
            rgba(0, 0, 0, 0) 100%
          );
          background-size: 100% 2px;
          background-position: 12px 12px;
          pointer-events: none;
          z-index: 100;
        }
        
        .x-scrollport, body {
          filter: brightness(1.10);
        }
        
        x-screen {
          position: relative !important;
          margin: 12px !important;
          width: calc(100% - 24px) !important;
          height: calc(100% - 24px) !important;
        }
        [id="hterm:terminal-overlay-cursor"] {
          inset: 12px !important;
        }
        .x-scrollport {
          padding: 12px !important;
        }
        
        .x-scrollport::after, x-scrollport::after {
          content: " ";
          display: block;
          position: absolute;
          top: 0; left: 0; right: 0; bottom: 0;
          background: radial-gradient(ellipse at 50% 45%, rgba(255, 113, 206, 0.10) 0%, transparent 70%),
                  radial-gradient(ellipse at center, transparent 60%, rgba(0, 0, 0, 0.26) 100%);
          pointer-events: none;
          z-index: 11;
        }
        body::after {
          content: " ";
          display: block;
          position: fixed;
          top: 0; left: 0; right: 0; bottom: 0;
          background: radial-gradient(ellipse at 50% 45%, rgba(255, 113, 206, 0.10) 0%, transparent 70%),
                  radial-gradient(ellipse at center, transparent 60%, rgba(0, 0, 0, 0.26) 100%);
          pointer-events: none;
          z-index: 101;
        }
        @keyframes cursorBlink {
          0%, 49% { opacity: 1; }
          50%, 100% { opacity: 0; }
        }
`;

t.prefs_.set('user-css-text', crtCss);

(function reflow(n) {
  const term = typeof window !== 'undefined' ? window.t : null;
  const sp = term && term.scrollPort_;
  if (sp && sp.screen_ && typeof sp.onResize_ === 'function') {
    [100, 500, 1500].forEach(ms => setTimeout(() => sp.onResize_(), ms));
  } else if (typeof window !== 'undefined' && n < 100) {
    setTimeout(() => reflow(n + 1), 50);
  }
})(0);
