// Ghost CRT: Blink Shell Theme
// Ported from Ghostty ghost profile + Calibrated WebKit CRT Shaders
// Generated by Ghost CRT Live Studio
// studio-state: {"enableBloom":true,"coreRadius":1.8,"coreOpacity":0.96,"haloRadius":8.5,"haloOpacity":0.7,"bloomAura":18,"enableScanlines":true,"scanProfile":"dura","scanHeight":1.5,"scanDarkness":0.3,"scanDuty":95,"enableGrille":false,"grilleMode":"mono","grilleWidth":1.5,"grilleDarkness":0.2,"grilleDuty":33,"enableTube":false,"ambientGlow":0.06,"vignetteDarkness":0.26,"brightness":1,"glare":true,"flicker":false,"fontFamily":"'JetBrains Mono', monospace","fontSize":18,"lineHeight":1.18,"letterSpacing":0,"background":"#0a0515","foreground":"#ff6a00","cursor":"#01cdfe","palette":["#120824","#ff5376","#05ffa1","#fffb96","#01cdfe","#b967ff","#01cdfe","#fffb96","#2c1654","#583300","#05ffa1","#fffb96","#01cdfe","#d084ff","#70e7ff","#ffffff"]}

const black        = '#120824';
const red          = '#ff5376';
const green        = '#05ffa1';
const yellow       = '#fffb96';
const blue         = '#01cdfe';
const magenta      = '#b967ff';
const cyan         = '#01cdfe';
const white        = '#fffb96';

const lightBlack   = '#2c1654';
const lightRed     = '#583300';
const lightGreen   = '#05ffa1';
const lightYellow  = '#fffb96';
const lightBlue    = '#01cdfe';
const lightMagenta = '#d084ff';
const lightCyan    = '#70e7ff';
const lightWhite   = '#ffffff';

// 1. Paleta ANSI calibrada (16 tons CRT)
t.prefs_.set('color-palette-overrides', [
  black, red, green, yellow,
  blue, magenta, cyan, white,
  lightBlack, lightRed, lightGreen, lightYellow,
  lightBlue, lightMagenta, lightCyan, lightWhite
]);

// 2. Cores base do terminal
t.prefs_.set('background-color', '#0a0515');
t.prefs_.set('foreground-color', '#ff6a00');
t.prefs_.set('cursor-color', '#01cdfe');
t.prefs_.set('cursor-blink', true);

// 3. Efeitos CRT calibrados
const crtCss = `
.x-row, .x-row span, x-row, x-row span {
          text-shadow:
    0 0 1.8px rgba(255, 106, 0, 0.96),
    0 0 8.5px rgba(255, 106, 0, 0.70),
    0 0 18px rgba(255, 106, 0, 0.32);
        }
        
        .x-scrollport::before, x-scrollport::before {
          content: " ";
          display: block;
          position: absolute;
          top: 0; left: 0; right: 0; bottom: 0;
          background-image: linear-gradient(
            rgba(0, 0, 0, 0) 5%,
            rgba(0, 0, 0, 0.30) 5%
          );
          background-size: 100% 1.5px;
          pointer-events: none;
          z-index: 10;
        }
        x-screen::before {
          content: " ";
          display: block;
          position: absolute;
          top: 0; left: 0; right: 0; bottom: 0;
          background-image: linear-gradient(
            rgba(0, 0, 0, 0) 5%,
            rgba(0, 0, 0, 0.30) 5%
          );
          background-size: 100% 1.5px;
          pointer-events: none;
          z-index: 100;
        }
        
        
        @keyframes cursorBlink {
          0%, 49% { opacity: 1; }
          50%, 100% { opacity: 0; }
        }
`;

t.prefs_.set('user-css-text', crtCss);
