// Ghost CRT: Blink Shell Theme
// Ported from Ghostty ghost profile + Calibrated WebKit CRT Shaders
// Generated by Ghost CRT Live Studio

const black        = '#120824';
const red          = '#ff5376';
const green        = '#05ffa1';
const yellow       = '#fffb96';
const blue         = '#01cdfe';
const magenta      = '#b967ff';
const cyan         = '#01cdfe';
const white        = '#fffb96';

const lightBlack   = '#2c1654';
const lightRed     = '#ff71ce';
const lightGreen   = '#05ffa1';
const lightYellow  = '#fffb96';
const lightBlue    = '#01cdfe';
const lightMagenta = '#d084ff';
const lightCyan    = '#70e7ff';
const lightWhite   = '#ffffff';

// 1. Paleta ANSI calibrada (16 tons CRT)
t.prefs_.set('color-palette-overrides', [
  black, red, green, yellow,
  blue, magenta, cyan, white,
  lightBlack, lightRed, lightGreen, lightYellow,
  lightBlue, lightMagenta, lightCyan, lightWhite
]);

// 2. Cores base do terminal
t.prefs_.set('background-color', '#0a0515');
t.prefs_.set('foreground-color', '#ff71ce');
t.prefs_.set('cursor-color', '#01cdfe');
t.prefs_.set('cursor-blink', true);

// 3. Efeitos CRT calibrados
const crtCss = `
.x-row, .x-row span, x-row, x-row span {
          text-shadow:
    0 0 1.8px rgba(255, 113, 206, 0.96),
    0 0 8.5px rgba(255, 113, 206, 0.70),
    0 0 18px rgba(255, 113, 206, 0.32);
        }
        
        .x-scrollport::before, x-scrollport::before {
          content: " ";
          display: block;
          position: absolute;
          top: 0; left: 0; right: 0; bottom: 0;
          background: linear-gradient(
            rgba(0, 0, 0, 0) 67%,
            rgba(0, 0, 0, 0.16) 67%
          );
          background-size: 100% 3px;
          pointer-events: none;
          z-index: 10;
        }
        x-screen::before {
          content: " ";
          display: block;
          position: absolute;
          top: 0; left: 0; right: 0; bottom: 0;
          background: linear-gradient(
            rgba(0, 0, 0, 0) 67%,
            rgba(0, 0, 0, 0.16) 67%
          );
          background-size: 100% 3px;
          pointer-events: none;
          z-index: 100;
        }
        
        .x-scrollport::after, x-scrollport::after {
          content: " ";
          display: block;
          position: absolute;
          top: 0; left: 0; right: 0; bottom: 0;
          background: radial-gradient(ellipse at 50% 45%, rgba(255, 113, 206, 0.06) 0%, transparent 70%),
                  radial-gradient(ellipse at center, transparent 60%, rgba(0, 0, 0, 0.26) 100%);
          pointer-events: none;
          z-index: 11;
        }
        x-screen::after {
          content: " ";
          display: block;
          position: absolute;
          top: 0; left: 0; right: 0; bottom: 0;
          background: radial-gradient(ellipse at 50% 45%, rgba(255, 113, 206, 0.06) 0%, transparent 70%),
                  radial-gradient(ellipse at center, transparent 60%, rgba(0, 0, 0, 0.26) 100%);
          pointer-events: none;
          z-index: 101;
        }
        @keyframes cursorBlink {
          0%, 49% { opacity: 1; }
          50%, 100% { opacity: 0; }
        }
`;

t.prefs_.set('user-css-text', crtCss);
