# Theme: Default Amber (Ported from Ghostty amber profile)
# Warm, softened amber phosphor with Terminess Nerd Font Mono
font_family      Terminess Nerd Font Mono
font_size        18.0

foreground            #e9b56e
background            #18120b
cursor                #e9b56e
cursor_text_color     #18120b
selection_foreground  #f5d4a0
selection_background  #514027

color0  #18120b
color1  #a57845
color2  #c49a5f
color3  #e0b472
color4  #9e8056
color5  #b58c58
color6  #c6a275
color7  #e9b56e
color8  #745535
color9  #cf9b60
color10 #e7bc7e
color11 #f5d4a0
color12 #caa77b
color13 #ddb887
color14 #edd0a4
color15 #f8dfb8
