# Theme: Monochrome Green (Ported from Ghostty green profile)
# Cooler, deeper green phosphor with Departure Mono
font_family      Departure Mono
font_size        16.5

foreground            #65d998
background            #08160f
cursor                #65d998
cursor_text_color     #08160f
selection_foreground  #a0edbf
selection_background  #204b34

color0  #08160f
color1  #4c9c6f
color2  #5dc98b
color3  #87d9a4
color4  #458e6c
color5  #60b082
color6  #65bda0
color7  #65d998
color8  #386b4c
color9  #75c294
color10 #85e9af
color11 #a0edbf
color12 #71c6a3
color13 #8ed4ab
color14 #8de4bd
color15 #b6f5d0
